import json
import sys
sys.stdout.reconfigure(encoding='utf-8')

# 英语思维记忆小提示库
ENGLISH_THOUGHTS = {
    # 衣物
    "shoes": "Like 'shush' - shoes help you walk quietly",
    "socks": "Rhymes with 'knocks' - knock knock with socks",
    "pants": "Short for 'pantaloons' - old word for trousers",
    "hat": "Sits on your head like a crown",
    "coat": "Like a coat of paint - covers you",
    "glove": "G + love - glove loves your hand",
    "umbrella": "Umbra = shadow, keeps you dry",
    "boots": "Help you step forward",
    "scarf": "Wrap it around like a hug for neck",
    
    # 食物
    "apple": "Red and crispy, an apple a day",
    "banana": "Yellow and curved",
    "orange": "Orange color and fruit",
    "bread": "Bake bread at home",
    "rice": "Staple food in Asia",
    "pizza": "Round with toppings",
    "chicken": "Farm bird, cluck cluck",
    "fish": "Swim in water",
    "egg": "Breakfast food, oval shape",
    "milk": "White drink from cows",
    "cheese": "Milk product, melts well",
    "honey": "Sweet from bees",
    "sugar": "Sweet white powder",
    "coffee": "Morning drink, bitter and dark",
    "tea": "Hot drink from leaves",
    "water": "Stay hydrated, drink water",
    
    # 动物
    "dog": "Man's best friend, wags tail",
    "cat": "Meow and purr",
    "bird": "Has wings, can fly",
    "fish": "Swim in water",
    "rabbit": "Long ears, hop around",
    "cow": "Says moo, gives milk",
    "pig": "Says oink, rolls in mud",
    "sheep": "Says baa, gives wool",
    "horse": "Big and strong, ride horses",
    "bear": "Big and strong, hibernates",
    "lion": "King of jungle, roars",
    "monkey": "Swing in trees, curious",
    "frog": "Jumps and says ribbit",
    "duck": "Says quack, swims in pond",
    "chicken": "Farm bird, gives eggs",
    
    # 学校
    "desk": "Sit at your desk to study",
    "chair": "Sit on the chair",
    "pencil": "Write with pencil",
    "pen": "Write with pen",
    "eraser": "Erase mistakes with eraser",
    "paper": "Write on paper",
    "homework": "Work to do at home",
    "test": "Test your knowledge",
    "grade": "Your score grade",
    "lesson": "Learn a new lesson",
    "teacher": "Teaches you at school",
    "student": "Learns at school",
    "library": "Borrow books from library",
    
    # 身体部位
    "head": "Think with your head",
    "face": "Show expressions on face",
    "eye": "See with your eyes",
    "nose": "Smell with nose",
    "mouth": "Eat and speak with mouth",
    "ear": "Hear with ears",
    "hand": "Hold with your hands",
    "foot": "Walk with your feet",
    "heart": "Heart pumps blood",
    "stomach": "Stomach growls when hungry",
    
    # 天气
    "sunny": "Sun is shining, bright day",
    "rainy": "Rain falls from sky",
    "cloudy": "Clouds cover the sky",
    "windy": "Wind blows, windy day",
    "snowy": "Snow falls, winter",
    "hot": "Very hot summer day",
    "cold": "Cold winter day",
    "warm": "Pleasantly warm spring day",
    
    # 颜色
    "red": "Color of fire and apples",
    "blue": "Color of sky and ocean",
    "green": "Color of grass and leaves",
    "yellow": "Color of sun and bananas",
    "orange": "Color of oranges",
    "purple": "Mix red and blue",
    "pink": "Light red, pretty pink",
    "brown": "Color of earth and wood",
    "black": "Darkest color",
    "white": "Lightest color",
    
    # 形容词
    "happy": "Smile when you're happy",
    "sad": "Cry when sad",
    "angry": "Roar when angry",
    "scared": "Shake when scared",
    "excited": "Jump up when excited",
    "tired": "Yawn when tired",
    "hungry": "Stomach growls when hungry",
    "thirsty": "Dry mouth when thirsty",
    "sick": "Go to doctor when sick",
    "healthy": "Eat well to stay healthy",
    "hot": "Sweat when hot",
    "cold": "Shiver when cold",
    "tall": "Grows tall",
    "short": "Not tall in height",
    "big": "Very large in size",
    "small": "Little and tiny",
    "new": "Brand new",
    "old": "Has lived a long time",
    "young": "Not old yet",
    "fast": "Run very fast",
    "slow": "Move slowly",
    "easy": "Not hard to do",
    "hard": "Difficult to do",
    "soft": "Not hard, soft pillow",
    "loud": "Very noisy, loud music",
    "quiet": "No noise, library is quiet",
    "dirty": "Needs cleaning, dirty hands",
    "clean": "No dirt, clean room",
    "wet": "Has water, wet clothes",
    "dry": "No water, dry ground",
    "full": "Stomach is full",
    "empty": "Nothing inside, empty cup",
    "heavy": "Hard to lift, heavy box",
    "light": "Easy to carry, light feather",
    "nice": "Kind and good, nice person",
    "mean": "Not nice, mean person",
    "kind": "Nice and helpful",
    "clever": "Smart and quick",
    "brave": "Not afraid, brave hero",
    "shy": "Nervous around people",
    "funny": "Makes you laugh",
    "boring": "No fun, boring class",
    "interesting": "Fun to learn",
    "beautiful": "Pretty and lovely",
    "delicious": "Yummy, delicious food",
    "safe": "Not dangerous",
    "dangerous": "Can hurt you",
    "busy": "Lots to do, busy day",
    "free": "No plans, free time",
    "ready": "Prepared, ready to go",
    "strong": "Can lift heavy things",
    "weak": "Not strong",
    "lazy": "Doesn't want to work",
    "different": "Not the same",
    "special": "Not ordinary",
    "strange": "Not normal",
    "broken": "Damaged, not working",
    "alive": "Living and breathing",
    
    # 动词
    "run": "Move fast on feet",
    "walk": "Move slowly on feet",
    "jump": "Push off and go up",
    "swim": "Move in water",
    "fly": "Go through air",
    "climb": "Go up, climb tree",
    "dance": "Move to music",
    "sing": "Make music with voice",
    "play": "Have fun, play games",
    "study": "Learn, study hard",
    "read": "Look at words, read book",
    "write": "Use pen, write words",
    "listen": "Hear with attention",
    "watch": "Look at, watch TV",
    "look": "Use your eyes, look!",
    "see": "Eyes see things",
    "hear": "Ears hear sounds",
    "think": "Use your brain, think",
    "know": "Have knowledge, I know",
    "understand": "Get the meaning",
    "remember": "Keep in memory",
    "forget": "Cannot recall, forget",
    "learn": "Get new knowledge",
    "help": "Give assistance",
    "share": "Give part to others",
    "wait": "Stay for a moment",
    "want": "Wish for something",
    "need": "Must have something",
    "like": "Enjoy something",
    "love": "Strong like, love it",
    "hate": "Strong dislike",
    "try": "Attempt to do",
    "start": "Begin doing",
    "stop": "End doing, stop!",
    "finish": "Complete, done",
    "open": "Make not closed",
    "close": "Make not open",
    "push": "Push the door",
    "pull": "Pull the handle",
    "throw": "Throw the ball",
    "catch": "Catch the ball",
    "kick": "Kick the ball",
    "hit": "Hit with force",
    "cut": "Cut with knife",
    "break": "Break in pieces",
    "fix": "Make work again",
    "wash": "Clean with water",
    "cook": "Make food",
    "eat": "Put food in mouth",
    "drink": "Put liquid in mouth",
    "sleep": "Rest at night",
    "wake": "Stop sleeping",
    "sit": "Lower to seat",
    "stand": "Rise up, stand up",
    "lie": "Lie down flat",
    "give": "Hand to others",
    "take": "Receive in hand",
    "buy": "Get with money",
    "sell": "Trade for money",
    "pay": "Give money",
    "use": "Put to use",
    "find": "Discover where it is",
    "lose": "Cannot find it",
    "draw": "Make pictures",
    "paint": "Use colors to paint",
    "win": "Be first, victory",
    "lose": "Not win, defeated",
    "decide": "Make a choice",
    "choose": "Pick one option",
    "agree": "Say yes, agree",
    "explain": "Make clear",
    "visit": "Go to see place",
    "meet": "See by arrangement",
    "grow": "Get bigger",
    "change": "Make different",
    "improve": "Make better",
    "hide": "Keep secret",
    "show": "Let others see",
    "breathe": "Air in and out",
    "feel": "Sense with body",
    "taste": "Sense with tongue",
    "smell": "Sense with nose",
    "hurt": "Feel pain",
    "burn": "Get hurt by fire",
    "freeze": "Get very cold",
    "melt": "Become liquid from heat",
    
    # 常见名词
    "bag": "Carry in a bag",
    "key": "Unlock the door",
    "phone": "Call on phone",
    "computer": "Type on computer",
    "bed": "Sleep in bed",
    "car": "Drive a car",
    "bus": "Ride the bus",
    "train": "Ride on train",
    "plane": "Fly in airplane",
    "ship": "Travel on big ship",
    "hospital": "Go to hospital when sick",
    "park": "Play in park",
    "beach": "Swim at beach",
    "river": "Swim in river",
    "lake": "Fish at the lake",
    "tree": "Grow in ground, tall plant",
    "flower": "Bloom and pretty",
    "grass": "Green grass under feet",
    "sun": "Rises in morning, sun",
    "moon": "Shines at night, full moon",
    "star": "Twinkle in night sky",
    "money": "Buy things with money",
    "gift": "Present for someone",
    "party": "Have a party",
    "birthday": "Special day born",
    "holiday": "Day off from work",
    "game": "Play a game",
    "song": "Sing a song",
    "story": "Tell a story",
    "letter": "Write a letter",
    "clock": "Clock tells time",
    "lamp": "Lamp lights up the room",
    "mirror": "See yourself in the mirror",
    "window": "Let light in through glass",
    "door": "Open the door to enter",
    "toy": "Play with toys",
    "book": "Read the book",
    
    # 短语动词
    "get up": "Rise from bed in morning",
    "wake up": "Stop sleeping",
    "put on": "Wear clothes, put on coat",
    "take off": "Remove clothes, take off shoes",
    "look at": "Direct your eyes toward",
    "look for": "Search for something",
    "look after": "Take care of someone",
    "give up": "Stop trying",
    "throw away": "Put in trash",
    "pick up": "Lift with hand",
    "find out": "Discover information",
    "come back": "Return to place",
    "go away": "Leave this place",
    "come in": "Enter a place",
    "sit down": "Lower to seat",
    "stand up": "Rise to standing",
    "lie down": "Put body flat",
    "turn on": "Start the machine",
    "turn off": "Stop the machine",
    "point out": "Show or indicate",
    "hand in": "Submit homework",
    "fill out": "Complete a form",
    "try on": "Wear to check fit",
    "take out": "Remove or buy food",
    "cut off": "Remove or disconnect",
    "break down": "Stop working",
    "bring up": "Raise topic or child",
    "carry on": "Continue doing",
    "come across": "Find or meet unexpectedly",
    "fall down": "Drop to ground",
    "get along": "Have good relationship",
    "grow up": "Become adult",
    "hang up": "End phone call",
    "keep up": "Maintain pace",
    "make up": "Invent or apply cosmetics",
    "pay back": "Return money",
    "pick out": "Choose from options",
    "point out": "Indicate or show",
    "put away": "Store or save",
    "put off": "Postpone",
    "run into": "Meet unexpectedly",
    "set up": "Establish or arrange",
    "show up": "Appear or arrive",
    "take care of": "Look after",
    "take off": "Remove or depart",
    "take on": "Accept task or hire",
    "take over": "Assume control",
    "throw away": "Discard as trash",
    "turn down": "Reject or lower volume",
    "turn up": "Appear or increase volume",
    "use up": "Consume completely",
    "wake up": "Stop sleeping",
    "work out": "Exercise or solve",
    "write down": "Record in writing",
}

def get_english_thought(word_en):
    """获取英语思维记忆提示"""
    word_lower = word_en.lower().strip()
    
    # 直接匹配
    if word_lower in ENGLISH_THOUGHTS:
        return ENGLISH_THOUGHTS[word_lower]
    
    return ""

def fix_memory_tips():
    """修复所有废话记忆小提示"""
    with open('content_backup/content_backup.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    fixed_count = 0
    removed_count = 0
    
    for date, words in data.items():
        for word in words:
            tip = word.get('memory_tip', '')
            
            # 检查是否是废话类型
            if '记住' in tip and '英文表达' in tip:
                # 用英语思维替换，或者删除
                new_tip = get_english_thought(word['word_en'])
                if new_tip:
                    word['memory_tip'] = new_tip
                    fixed_count += 1
                else:
                    word['memory_tip'] = ""  # 留空
                    removed_count += 1
    
    # 保存修复后的文件
    with open('content_backup/content_backup.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"修复完成！")
    print(f"- 有英语思维提示: {fixed_count} 个")
    print(f"- 删除废话提示: {removed_count} 个")
    print(f"- 总共处理: {fixed_count + removed_count} 个")

if __name__ == '__main__':
    fix_memory_tips()
