import json
import re
import sys
sys.stdout.reconfigure(encoding='utf-8')

# 英语思维记忆小提示库（用英语思维解释）
ENGLISH_THOUGHTS = {
    # 衣物类
    "shoes": "Like 'shush' - shoes help you walk quietly",
    "socks": "Rhymes with 'knocks' - you knock on the door with your socks",
    "pants": "Short for 'pantaloons' - old word for trousers",
    "hat": "Short for 'chateau' - sounds like a castle on your head",
    "shirt": "Part of '-shirt' in 'undershirt'",
    "jacket": "Like 'jack' - a short coat, quick to wear",
    "dress": "One word, covers whole body",
    "skirt": "Skirt hangs from the waist down",
    "glove": "G + love - glove loves your hand",
    "umbrella": "Umbra = shadow, keeps you in the shade",
    "boots": "One step ahead - boots help you go forward",
    "scarf": "Wrap it around your neck like a 'scarf' of protection",
    
    # 常见名词
    "coat": "Like 'coat' of paint - covers your body",
    "pillow": "Soft and fluffy, like a 'pillow' cloud",
    "blanket": "Blanket of snow - covers the bed",
    "bedroom": "Room with a bed",
    "kitchen": "Cook in the kitchen, like a 'kitchen' duty",
    "bathroom": "Where you take a bath",
    "mirror": "See yourself in the mirror",
    "clock": "The 'clock' ticks away time",
    "alarm clock": "Alarm + clock - wakes you up",
    "photo": "Short for photograph - a still picture",
    "music": "Mu + sic - sounds magical",
    "song": "Sing a song",
    "TV": "Short for television - watch shows",
    "picture": "A still image",
    
    # 形容词
    "lazy": "Lazy people lie around all day",
    "nice": "Nice people are kind to others",
    "comfy": "Comfortable - comfy sounds cozy",
    "fun": "Fun time, happy moments",
    "tidy": "Tidy room, everything in its place",
    "dirty": "Needs cleaning, opposite of clean",
    "quiet": "No noise, very quiet",
    "loud": "Lots of noise, very loud",
    "fast": "Quick speed, run fast",
    "slow": "Opposite of fast, take your time",
    "big": "Large size, big difference",
    "small": "Little size, tiny and small",
    "tall": "Height, tall building",
    "short": "Not tall, short person",
    "happy": "Good feelings, smile and be happy",
    "sad": "Bad feelings, cry when sad",
    "angry": "Strong feelings, want to shout when angry",
    "tired": "Need rest, so tired",
    "hungry": "Need food, stomach growls when hungry",
    "thirsty": "Need water, dry mouth when thirsty",
    "sick": "Not feeling well, need medicine",
    "healthy": "Strong and well, eat healthy food",
    
    # 动词
    "sing": "Your voice makes music when you sing",
    "dance": "Move to the music, dance around",
    "hug": "Wrap arms around someone, give a hug",
    "kiss": "Press lips together, give a kiss",
    "wash": "Use water to clean, wash your hands",
    "brush": "Move back and forth to clean, brush teeth",
    "cook": "Make food, cook a meal",
    "clean": "Make clean, tidy up the room",
    "open": "Open the door, open a book",
    "close": "Close the door, close your eyes",
    "play": "Have fun, play games",
    "study": "Learn new things, study hard",
    "read": "Look at words, read a book",
    "write": "Use a pen, write your name",
    "listen": "Hear with attention, listen carefully",
    "watch": "Look at something, watch TV",
    "help": "Give a hand, help others",
    "share": "Give part to others, share with friends",
    "wait": "Stay for a moment, wait here",
    "walk": "Move with feet, walk to school",
    "run": "Move fast with feet, run away",
    "jump": "Push off with feet, jump high",
    "swim": "Move in water, swim in the pool",
    "fly": "Birds can fly in the sky",
    "climb": "Go up, climb the tree",
    "sleep": "Rest at night, go to sleep",
    "wake up": "Stop sleeping, wake up early",
    "sit down": "Put your bottom on a chair, sit down",
    "stand up": "Put feet on ground, stand up straight",
    "put on": "Wear clothes, put on your coat",
    "take off": "Remove clothes, take off shoes",
    "get dressed": "Put on clothes, get dressed in the morning",
    "turn on": "Start the machine, turn on the light",
    "turn off": "Stop the machine, turn off TV",
    
    # 日常用语
    "please": "Say please when asking - polite word",
    "thank you": "Appreciate help - say thank you",
    "sorry": "Apologize - say sorry",
    "excuse me": "Get attention politely",
    "hello": "Greet people, say hello",
    "goodbye": "Parting word, say goodbye",
    "yes": "Agree, say yes",
    "no": "Disagree, say no",
    "OK": "All right, that's OK",
    "great": "Very good, that's great",
    "wow": "Surprise sound, wow!",
    "ouch": "Pain sound, ouch!",
    
    # 家庭成员
    "mom": "Mother, call her mom",
    "dad": "Father, call him dad",
    "sister": "Girl sibling, my sister",
    "brother": "Boy sibling, my brother",
    "grandma": "Mother's or father's mother",
    "grandpa": "Mother's or father's father",
    "friend": "Someone you like, my friend",
    "teacher": "Teaches you at school",
    "doctor": "Helps you when sick",
    "student": "Learns at school",
    
    # 时间
    "today": "This very day",
    "tomorrow": "The day after today",
    "yesterday": "The day before today",
    "morning": "Early part of day",
    "afternoon": "Midday to evening",
    "evening": "End of day, before night",
    "night": "Dark time, sleep at night",
    "weekend": "Saturday and Sunday",
    "Monday": "First day of school week",
    "Tuesday": "Two-sday, day two",
    "Wednesday": "Middle of week",
    "Thursday": "Four-sday, day four",
    "Friday": "Five-sday, last school day",
    "Saturday": "Satur-day, weekend begins",
    "Sunday": "Sun's day, rest day",
    
    # 食物
    "breakfast": "Break your fast - first meal",
    "lunch": "Midday meal",
    "dinner": "Evening meal, main meal",
    "snack": "Small food between meals",
    "water": "Drink water, stay hydrated",
    "juice": "Drink from fruits",
    "milk": "White drink from cows",
    "bread": "Made from dough, bake bread",
    "rice": "Eat rice with meals",
    "egg": "Breakfast food, oval shape",
    "apple": "Red fruit, crisp and sweet",
    "banana": "Yellow fruit, long shape",
    "orange": "Orange fruit, citrus taste",
    "chicken": "Meat from chicken",
    "fish": "Sea food, swim in water",
    "vegetable": "Healthy plant food",
    "carrot": "Orange vegetable, good for eyes",
    "tomato": "Red vegetable, used in sauce",
    "potato": "Brown vegetable, grow underground",
    "salad": "Mix of vegetables",
    "soup": "Hot liquid food, drink from bowl",
    "pizza": "Round flat bread with toppings",
    "hamburger": "Meat between two buns",
    "cookie": "Sweet baked snack",
    "cake": "Sweet dessert, celebrate with cake",
    "ice cream": "Cold sweet treat, summer favorite",
    "candy": "Sweet sugar treat",
    "chocolate": "Dark sweet treat, made from cocoa",
    "popcorn": "Puffy snack, watch movies with popcorn",
    "coffee": "Hot brown drink, morning drink",
    "tea": "Hot drink from leaves",
    "sugar": "Sweet powder",
    "salt": "White crystals, flavor food",
    "butter": "Spread on bread",
    "cheese": "Dairy product, melts well",
    "honey": "Sweet from bees",
    "soup": "Hot liquid food",
    
    # 动物
    "dog": "Bark and wag tail, man's best friend",
    "cat": "Meow and purr, independent pet",
    "bird": "Has wings, can fly",
    "fish": "Swim in water, breathe with gills",
    "rabbit": "Long ears, hop around",
    "mouse": "Small, gray, squeaks",
    "horse": "Big, ride on its back",
    "cow": "Says moo, gives milk",
    "sheep": "Says baa, gives wool",
    "pig": "Says oink, roll in mud",
    "chicken": "Says cluck, gives eggs",
    "duck": "Says quack, webbed feet",
    "frog": "Jumps, says ribbit",
    "snake": "Slithers, no legs",
    "turtle": "Slow, carries shell on back",
    "elephant": "Big, long trunk",
    "monkey": "Swings in trees, curious",
    "bear": "Big and strong, hibernates",
    "lion": "King of jungle, roars",
    "tiger": "Stripes, powerful hunter",
    "panda": "Black and white, eats bamboo",
    "zebra": "Black and white stripes",
    "giraffe": "Long neck, tallest animal",
    "deer": "Antlers, graceful runner",
    "wolf": "Howls at moon, lives in packs",
    "fox": "Clever and sly, bush tail",
    "squirrel": "Climbs trees, stores nuts",
    "bee": "Makes honey, can sting",
    "ant": "Works hard, lives in groups",
    "spider": "Eight legs, makes web",
    "butterfly": "Beautiful wings, transforms from caterpillar",
    "ladybug": "Red with black spots",
    "bee": "Buzzes around flowers",
    
    # 地点
    "home": "Where you live, feel safe",
    "school": "Learn and study",
    "park": "Green space, play outside",
    "zoo": "See animals",
    "hospital": "Get better when sick",
    "store": "Buy things",
    "restaurant": "Eat food made for you",
    "library": "Borrow and read books",
    "museum": "See art and history",
    "beach": "Sand and sea, vacation spot",
    "mountain": "High land, climb up",
    "river": "Flowing water, long and winding",
    "lake": "Still water, like a pond",
    "forest": "Many trees, wild animals",
    "island": "Land surrounded by water",
    "garden": "Grow plants and flowers",
    
    # 学校
    "class": "Time to learn",
    "desk": "Sit at your desk",
    "chair": "Sit on the chair",
    "book": "Read the book",
    "pencil": "Write with pencil",
    "pen": "Write with pen",
    "paper": "Write on paper",
    "eraser": "Erase mistakes",
    "ruler": "Measure and draw straight lines",
    "bag": "Carry your things",
    "homework": "Work to do at home",
    "test": "Show what you learned",
    "grade": "Score on your work",
    "lesson": "Time to learn something new",
    "problem": "Question to solve",
    "answer": "Response to question",
    "question": "Ask a question",
    "story": "Tell a story",
    "word": "Unit of language",
    "sentence": "Group of words",
    "letter": "ABC of alphabet",
    "number": "Count with numbers",
    "math": "Numbers and problems",
    "science": "Learn about the world",
    "history": "Learn about the past",
    "art": "Create and express",
    "music": "Sounds and rhythm",
    "PE": "Physical exercise, play sports",
    "game": "Play a game",
    "sport": "Active physical game",
    "team": "Group playing together",
    
    # 身体部位
    "head": "Top of body, think with head",
    "face": "Front of head, show expressions",
    "eye": "See with eyes",
    "nose": "Smell and breathe",
    "mouth": "Eat and speak",
    "ear": "Hear with ears",
    "hand": "Touch and hold",
    "foot": "Walk with feet",
    "arm": "Reach and grab",
    "leg": "Stand and walk",
    "finger": "Point and touch",
    "toe": "Wiggle your toes",
    "hair": "On top of head",
    "tooth": "Bite and chew, brush teeth",
    "teeth": "Many teeth, plural of tooth",
    "body": "Whole you, head and limbs",
    "skin": "Covers your body",
    "bone": "Inside your body, skeleton",
    "heart": "Beats in chest, pump blood",
    "brain": "Think and remember",
    "stomach": "Digest food, feel hungry",
    
    # 天气
    "sunny": "Sun is shining, bright day",
    "rainy": "Water falls from sky",
    "cloudy": "Clouds cover sky",
    "windy": "Air moves fast, windy day",
    "snowy": "Snow falls, winter weather",
    "stormy": "Thunder and lightning",
    "hot": "High temperature, summer heat",
    "cold": "Low temperature, winter chill",
    "warm": "Pleasant temperature",
    "cool": "Slightly cold, autumn breeze",
    
    # 颜色
    "red": "Color of fire and apples",
    "blue": "Color of sky and ocean",
    "green": "Color of grass and leaves",
    "yellow": "Color of sun and bananas",
    "orange": "Color of oranges",
    "purple": "Mix of red and blue",
    "pink": "Light red",
    "brown": "Color of earth and wood",
    "black": "Darkest color",
    "white": "Lightest color",
    "gray": "Between black and white",
    "color": "Different shades and hues",
    
    # 数字
    "one": "1, first number",
    "two": "2, a pair",
    "three": "3, a triplet",
    "four": "4, four corners",
    "five": "5, five fingers",
    "six": "6, half a dozen",
    "seven": "7, lucky number",
    "eight": "8, two circles",
    "nine": "9, almost ten",
    "ten": "10, complete hands",
    "hundred": "100, big number",
    
    # 其他常见词
    "toy": "Play with toys",
    "game": "Have fun playing games",
    "gift": "Present for someone",
    "party": "Fun celebration with friends",
    "birthday": "Your special day",
    "balloon": "Float in air, party decoration",
    "candle": "Light on birthday cake",
    "door": "Open and close to enter",
    "window": "Look through glass",
    "key": "Unlock the door",
    "phone": "Talk to people far away",
    "computer": "Type and browse online",
    "table": "Eat on the table",
    "chair": "Sit on the chair",
    "bed": "Sleep in bed",
    "lamp": "Light up the room",
    "TV": "Watch shows",
    "radio": "Listen to music and news",
    "newspaper": "Read daily news",
    "letter": "Write to friends",
    "stamp": "Put on letter to send",
    "postcard": "Picture with short message",
    "bank": "Keep money safe",
    "money": "Buy things with money",
    "price": "How much it costs",
    "shop": "Buy things",
    "buy": "Get with money",
    "sell": "Give for money",
    "pay": "Give money for things",
    "change": "Money back after paying",
    "expensive": "Costs a lot",
    "cheap": "Costs little",
    "free": "No cost",
    "street": "Road in the city",
    "road": "Way to travel",
    "bus": "Public transportation",
    "car": "Drive yourself",
    "taxi": "Hire a car with driver",
    "train": "Runs on tracks",
    "plane": "Fly through the air",
    "ship": "Sail on water",
    "boat": "Small water vehicle",
    "ticket": "Get on the bus or train",
    "stop": "Come to a stop",
    "wait": "Stay for a moment",
    "cross": "Go to the other side",
    "left": "Opposite of right",
    "right": "Opposite of left",
    "up": "Opposite of down",
    "down": "Opposite of up",
    "in": "Inside something",
    "out": "Outside something",
    "on": "On top of something",
    "under": "Below something",
    "near": "Close to something",
    "far": "A long way away",
    "every": "Each one, all of them",
    "some": "A few, not all",
    "many": "A lot of things",
    "much": "A lot of uncountable",
    "all": "The whole thing, everything",
    "other": "Different one",
    "another": "One more",
    "most": "The largest part",
    "thing": "Object or stuff",
    "place": "Location or spot",
    "time": "When something happens",
    "way": "How to do something",
    "year": "12 months",
    "day": "24 hours",
    "week": "7 days",
    "month": "About 30 days",
    "hour": "60 minutes",
    "minute": "60 seconds",
    "second": "Very short time",
    "spring": "Season of flowers",
    "summer": "Hot season",
    "autumn": "Season of falling leaves",
    "winter": "Cold season with snow",
    "holiday": "Vacation time, special day",
    "vacation": "Time off from work or school",
    "trip": "Journey somewhere",
    "tour": "Visit places",
    "map": "Show places",
    "plan": "Think ahead, make a plan",
    "idea": "Think of an idea",
    "work": "Do a job",
    "job": "Your work task",
    "rest": "Relax and recover",
    "need": "Must have something",
    "want": "Wish for something",
    "like": "Enjoy something",
    "love": "Deep like, love something",
    "hate": "Strong dislike",
    "use": "Use something for purpose",
    "try": "Attempt something",
    "start": "Begin something",
    "stop": "End something",
    "keep": "Hold onto something",
    "let": "Allow something",
    "call": "Use phone, call someone",
    "feel": "Sense with body",
    "become": "Change into something",
    "leave": "Go away from",
    "put": "Place something somewhere",
    "mean": "Signify something",
    "keep": "Continue to have",
    "set": "Put in position",
    "learn": "Gain knowledge",
    "change": "Make different",
    "lead": "Guide others",
    "understand": "Comprehend meaning",
    "watch": "Look at something",
    "live": "Be alive, reside",
    "believe": "Think something is true",
    "hold": "Grasp with hands",
    "bring": "Carry to here",
    "happen": "Take place",
    "write": "Write words down",
    "provide": "Give something",
    "sit": "Put weight on seat",
    "stand": "Rise to vertical",
    "lose": "Cannot find, not win",
    "pay": "Give money",
    "meet": "Come together",
    "include": "Have as part",
    "continue": "Keep going",
    "set": "Put in place",
    "learn": "Acquire knowledge",
    "explain": "Make clear",
    "believe": "Accept as truth",
    "decide": "Make a choice",
    "like": "Prefer, enjoy",
    "love": "Strong affection",
    "hate": "Strong dislike",
    "hope": "Wish for something",
    "fear": "Feel scared",
    "wonder": "Be curious",
    "remember": "Recall from memory",
    "forget": "Cannot recall",
    "think": "Use brain",
    "know": "Have knowledge",
    "hear": "Sound reaches ears",
    "see": "Light enters eyes",
    "look": "Use eyes intentionally",
    "watch": "Observe over time",
    "touch": "Feel with hands",
    "taste": "Sense with tongue",
    "smell": "Sense with nose",
    "wake up": "Stop sleeping",
    "get up": "Rise from bed",
    "go to bed": "Lie down to sleep",
    "fall asleep": "Begin sleeping",
    "take a shower": "Wash body",
    "brush teeth": "Clean teeth",
    "wash face": "Clean face",
    "eat breakfast": "Morning meal",
    "have lunch": "Midday meal",
    "have dinner": "Evening meal",
    "go to school": "Attend school",
    "go home": "Return home",
    "do homework": "School work at home",
    "go to sleep": "Begin sleeping",
    "wake up": "Stop sleeping",
    "get dressed": "Put on clothes",
    "take a bath": "Soak in water",
    "go shopping": "Buy things",
    "go swimming": "Enter water to swim",
    "go hiking": "Walk in nature",
    "go camping": "Sleep outdoors",
    "go fishing": "Catch fish",
    "go running": "Run for exercise",
    "go walking": "Walk for exercise",
    "ride a bike": "Pedal two wheels",
    "drive a car": "Control a vehicle",
    "take a bus": "Ride public transport",
    "take a train": "Ride on tracks",
    "take a plane": "Fly through air",
    "take a taxi": "Hire a car",
    "cross the street": "Walk to other side",
    "turn left": "Go left direction",
    "turn right": "Go right direction",
    "go straight": "Continue forward",
    "come back": "Return to place",
    "go ahead": "Proceed forward",
    "come in": "Enter a place",
    "go out": "Exit a place",
    "sit down": "Lower to seat",
    "stand up": "Rise to standing",
    "lie down": "Horizontal position",
    "pick up": "Take with hand",
    "put down": "Release to surface",
    "give up": "Stop trying",
    "throw away": "Discard as trash",
    "pick out": "Choose from options",
    "try on": "Wear to check fit",
    "take off": "Remove clothing",
    "put on": "Wear clothing",
    "turn on": "Start device",
    "turn off": "Stop device",
    "open up": "Make open",
    "close down": "Stop operating",
    "wake up": "Stop sleeping",
    "clean up": "Make clean",
    "grow up": "Become adult",
    "cheer up": "Become happier",
    "break down": "Stop working",
    "calm down": "Become peaceful",
    "dress up": "Wear nice clothes",
    "hang out": "Spend time casually",
    "hang up": "End phone call",
    "look up": "Search for information",
    "make up": "Invent or apply cosmetics",
    "mix up": "Confuse or combine",
    "show up": "Arrive and appear",
    "shut up": "Stop talking",
    "speed up": "Go faster",
    "slow down": "Go slower",
    "straighten up": "Make neat",
    "warm up": "Prepare with gentle activity",
    "clean up": "Tidy and organize",
    "grow up": "Become older",
    "mess up": "Make mistake or disorder",
    "write down": "Record in writing",
    "point out": "Indicate or show",
    "find out": "Discover information",
    "come out": "Be published or appear",
    "go out": "Leave home for activity",
    "cut out": "Stop or remove",
    "blow up": "Explode or inflate",
    "bring up": "Mention or raise",
    "carry out": "Perform or execute",
    "come up with": "Think of or generate",
    "do over": "Repeat from beginning",
    "fill out": "Complete a form",
    "get across": "Communicate clearly",
    "get along": "Have good relationship",
    "get away": "Escape or leave",
    "get back": "Return or recover",
    "get by": "Survive or manage",
    "get down": "Feel depressed",
    "get over": "Recover from",
    "give away": "Donate or reveal",
    "give back": "Return something",
    "give in": "Surrender or submit",
    "give out": "Distribute or emit",
    "go ahead": "Proceed or continue",
    "go along": "Accompany or agree",
    "go by": "Pass time or location",
    "go for": "Choose or attempt",
    "go off": "Sound an alarm or explode",
    "go on": "Continue or happen",
    "go over": "Review or cross",
    "go through": "Experience or examine",
    "hand in": "Submit or give",
    "hand out": "Distribute",
    "hand over": "Transfer possession",
    "have on": "Be wearing",
    "hold on": "Wait or grasp",
    "hold out": "Resist or extend",
    "keep on": "Continue doing",
    "keep up": "Maintain pace or level",
    "let down": "Disappoint",
    "look after": "Take care of",
    "look ahead": "Plan for future",
    "look around": "Examine surroundings",
    "look at": "Direct eyes toward",
    "look for": "Search for",
    "look forward to": "Anticipate with pleasure",
    "look into": "Investigate",
    "look out": "Be careful or watch",
    "look over": "Review quickly",
    "look up": "Search or raise eyes",
    "make out": "Understand or progress",
    "make up": "Invent or compose",
    "pass away": "Die",
    "pass on": "Die or transfer",
    "pass out": "Lose consciousness",
    "pay back": "Return money or revenge",
    "pay off": "Succeed or settle debt",
    "pick up": "Lift or learn",
    "point out": "Indicate or show",
    "pull over": "Drive to side",
    "pull up": "Approach or raise",
    "put away": "Store or save",
    "put back": "Return to place",
    "put down": "Place or suppress",
    "put off": "Postpone",
    "put out": "Extinguish or publish",
    "put up": "Build or tolerate",
    "put up with": "Tolerate or endure",
    "result in": "Cause or lead to",
    "run across": "Meet unexpectedly",
    "run away": "Flee or escape",
    "run into": "Meet or collide",
    "run off": "Leave quickly or print",
    "run out": "Be used up",
    "run over": "Drive over or review",
    "see off": "Bid farewell to traveler",
    "see to": "Take care of",
    "sell out": "Sell all inventory",
    "send back": "Return or reject",
    "send out": "Distribute or emit",
    "set aside": "Reserve or ignore",
    "set off": "Begin journey or trigger",
    "set out": "Begin journey or organize",
    "set up": "Establish or arrange",
    "show off": "Display proudly",
    "show up": "Appear or arrive",
    "shut down": "Close or stop",
    "shut off": "Turn off or isolate",
    "shut up": "Be quiet or confine",
    "sit down": "Lower to seat",
    "sit up": "Rise to sitting",
    "slow down": "Reduce speed",
    "snap out of": "Recover from mood",
    "sort out": "Organize or resolve",
    "spell out": "Explain clearly",
    "stand by": "Support or wait",
    "stand for": "Represent or tolerate",
    "stand out": "Be prominent",
    "stand up": "Rise or last",
    "stand up for": "Defend or support",
    "stay up": "Remain awake",
    "step down": "Resign or lower",
    "step up": "Increase or advance",
    "stick to": "Persist or follow",
    "stick with": "Continue with",
    "stop by": "Visit briefly",
    "stop off": "Break journey",
    "switch off": "Turn off",
    "switch on": "Turn on",
    "take after": "Resemble parent",
    "take apart": "Disassemble",
    "take away": "Remove or buy food",
    "take back": "Return or retract",
    "take care of": "Look after",
    "take down": "Remove or record",
    "take in": "Understand or deceive",
    "take off": "Remove or depart",
    "take on": "Accept task or hire",
    "take out": "Remove or invite",
    "take over": "Assume control",
    "take up": "Begin or occupy",
    "talk back": "Reply defiantly",
    "talk into": "Persuade to do",
    "talk over": "Discuss thoroughly",
    "tell apart": "Distinguish",
    "tell off": "Scold severely",
    "tell on": "Inform on",
    "think ahead": "Plan for future",
    "think back": "Recall past",
    "think over": "Consider carefully",
    "think up": "Invent or create",
    "throw away": "Discard as trash",
    "throw out": "Reject or discard",
    "tie up": "Fasten or occupy",
    "top up": "Refill to full",
    "try on": "Test fit of clothing",
    "try out": "Test or audition",
    "turn around": "Reverse direction",
    "turn down": "Reject or lower volume",
    "turn into": "Become or transform",
    "turn off": "Stop or deactivate",
    "turn on": "Start or activate",
    "turn out": "Attend or prove to be",
    "turn over": "Flip or consider",
    "turn up": "Appear or increase volume",
    "use up": "Consume completely",
    "wait for": "Expect or anticipate",
    "wait on": "Serve or attend",
    "wait up": "Stay awake for",
    "wake up": "Stop sleeping",
    "warm up": "Prepare or reheat",
    "warn about": "Alert to danger",
    "wear down": "Diminish gradually",
    "wear off": "Diminish and disappear",
    "wear out": "Use until damaged",
    "wind up": "Conclude or tease",
    "wipe out": "Destroy or exhaust",
    "work out": "Exercise or solve",
    "worry about": "Feel anxious",
    "wrap up": "Conclude or dress warmly",
    "write down": "Record in writing",
    "write off": "Cancel or debt",
    "zone out": "Become distracted",
    
    # 形容词更多
    "clever": "Smart and quick-witted",
    "silly": "Funny but not smart",
    "stupid": "Not smart at all",
    "brave": "Not afraid, courageous",
    "shy": "Nervous around people",
    "polite": "Good manners",
    "rude": "Bad manners",
    "kind": "Nice to others",
    "mean": "Unkind or average",
    "fair": "Just and equal",
    "rich": "Have lots of money",
    "poor": "Not much money",
    "strong": "Powerful physically",
    "weak": "Not strong physically",
    "young": "Not old",
    "old": "Not young",
    "pretty": "Attractive (usually girls)",
    "handsome": "Attractive (usually boys)",
    "ugly": "Not attractive",
    "delicious": "Very tasty food",
    "yucky": "Tastes bad",
    "fresh": "New and clean",
    "stale": "Old and not fresh",
    "full": "Have eaten enough",
    "empty": "Nothing inside",
    "heavy": "Weighs a lot",
    "light": "Not heavy or bright",
    "dark": "Little light",
    "bright": "Lots of light or smart",
    "wide": "Not narrow",
    "narrow": "Not wide",
    "thick": "Not thin",
    "thin": "Not thick",
    "deep": "Not shallow",
    "shallow": "Not deep",
    "high": "Not low (position)",
    "low": "Not high (position)",
    "long": "Not short (length)",
    "short": "Not long or tall",
    "easy": "Not difficult",
    "difficult": "Hard to do",
    "hard": "Difficult or solid",
    "soft": "Not hard",
    "rough": "Not smooth",
    "smooth": "Not rough",
    "dry": "No water",
    "wet": "Has water",
    "clean": "No dirt",
    "dirty": "Has dirt",
    "safe": "Not dangerous",
    "dangerous": "Can hurt you",
    "busy": "Lots to do",
    "free": "No plans, no cost",
    "ready": "Prepared",
    "afraid": "Feeling fear",
    "worried": "Feeling concern",
    "proud": "Feel good about self",
    "shame": "Feel embarrassed",
    "interested": "Want to know more",
    "bored": "Nothing interesting",
    "excited": "Very happy and energetic",
    "nervous": "Worried and anxious",
    "relaxed": "Calm and peaceful",
    "stressed": "Tense and worried",
    "serious": "Not joking",
    "important": "Matters a lot",
    "interesting": "Catches attention",
    "strange": "Not normal",
    "normal": "Usual and expected",
    "special": "Not ordinary",
    "common": "Seen often",
    "rare": "Not common",
    "real": "True and genuine",
    "fake": "Not real",
    "possible": "Can happen",
    "impossible": "Cannot happen",
    "necessary": "Needed",
    "different": "Not the same",
    "same": "Identical",
    "true": "Correct and factual",
    "false": "Not true",
    "perfect": "No mistakes",
    "broken": "Damaged and not working",
    "open": "Not closed",
    "closed": "Not open",
    "private": "Not for everyone",
    "public": "For everyone",
    "native": "From this place originally",
    "foreign": "From another country",
    "local": "From this area",
    "international": "Across countries",
    "modern": "New and current",
    "traditional": "Following old ways",
    "popular": "Liked by many",
    "famous": "Known by many",
    "unknown": "Not known",
    "free": "No cost or restriction",
    "natural": "From nature",
    "artificial": "Made by humans",
    "medical": "Related to medicine",
    "military": "Related to army",
    "political": "Related to government",
    "religious": "Related to religion",
    "cultural": "Related to culture",
    "social": "Related to society",
    "personal": "Private and individual",
    "public": "Open to everyone",
    "secret": "Hidden from others",
    "official": "From authority",
    "friendly": "Nice like a friend",
    "lonely": "Feeling alone",
    "helpful": "Gives help",
    "useless": "Not helpful",
    "powerful": "Has great power",
    "helpless": "Cannot help self",
    "careful": "Watch out for danger",
    "careless": "Not paying attention",
    "useful": "Can be used well",
    "wonderful": "Very amazing",
    "terrible": "Very bad",
    "awful": "Extremely bad",
    "excellent": "Very good",
    "amazing": "Very surprising",
    "terrifying": "Very scary",
    "boring": "Not interesting",
    "confusing": "Hard to understand",
    "surprising": "Not expected",
    "embarrassing": "Makes you feel shame",
    "challenging": "Difficult but doable",
    "enjoyable": "Pleasant experience",
    "satisfying": "Fulfilling result",
    "frustrating": "Making you angry",
    "exciting": "Full of excitement",
    "disappointing": "Not as good as expected",
    "comfortable": "Feels good physically",
    "uncomfortable": "Feels bad physically",
    "adorable": "Very cute",
    "horrible": "Very unpleasant",
    "valuable": "Worth a lot",
    "worthless": "Has no value",
    "expensive": "Costs a lot",
    "inexpensive": "Does not cost much",
    "valuable": "Important and useful",
    "useless": "Has no purpose",
    "empty": "Nothing inside",
    "crowded": "Too many people",
    "peaceful": "Quiet and calm",
    "noisy": "Very loud",
    "quiet": "Very soft sound",
    "loud": "Very high volume",
    "fast": "High speed",
    "slow": "Low speed",
    "quick": "Done in short time",
    "sudden": "Happens without warning",
    "gradual": "Happens slowly",
    "immediate": "Right now",
    "permanent": "Forever",
    "temporary": "Not forever",
    "clear": "Easy to see or understand",
    "obvious": "Very clear and evident",
    "hidden": "Not visible",
    "simple": "Not complicated",
    "complicated": "Hard to understand",
    "basic": "Fundamental and simple",
    "advanced": "Complex and high-level",
    "direct": "Straight to the point",
    "indirect": "Not straightforward",
    "positive": "Good or affirmative",
    "negative": "Bad or saying no",
    "active": "Doing things",
    "passive": "Not doing anything",
    "correct": "Right and accurate",
    "incorrect": "Wrong",
    "accurate": "Correct and precise",
    "precise": "Exact and detailed",
    "vague": "Not specific",
    "specific": "Clearly defined",
    "general": "Not specific",
    "particular": "Special and specific",
    "certain": "Sure and definite",
    "uncertain": "Not sure",
    "definite": "Clear and certain",
    "possible": "Can happen",
    "probable": "Likely to happen",
    "unlikely": "Not likely",
    "willing": "Want to do",
    "unwilling": "Do not want to do",
    "able": "Capable of doing",
    "unable": "Not capable",
    "capable": "Able and competent",
    "incapable": "Not able",
    "qualified": "Has necessary skills",
    "experienced": "Has lots of practice",
    "inexperienced": "New and untested",
    "professional": "Related to job",
    "amateur": "Not professional",
    "serious": "Not joking",
    "relaxed": "Calm and easy",
    "formal": "Official and proper",
    "informal": "Casual and relaxed",
    "private": "Not public",
    "public": "Open to all",
    "honest": "Tells the truth",
    "dishonest": "Tells lies",
    "loyal": "Faithful to someone",
    "independent": "Does not need others",
    "dependent": "Needs others",
    "reliable": "Can be trusted",
    "unreliable": "Cannot be trusted",
    "responsible": "Can be counted on",
    "irresponsible": "Not dependable",
    "mature": "Grown up thinking",
    "immature": "Childish thinking",
    "generous": "Gives to others",
    "selfish": "Only thinks of self",
    "selfless": "Thinks of others first",
    "modest": "Does not brag",
    "arrogant": "Thinks too highly of self",
    "humble": "Modest and respectful",
    "confident": "Sure of self",
    "insecure": "Not sure of self",
    "patient": "Can wait calmly",
    "impatient": "Cannot wait",
    "determined": "Has strong will",
    "hesitant": "Not sure what to do",
    "decisive": "Makes decisions quickly",
    "indecisive": "Cannot decide",
    "organized": "Has good order",
    "disorganized": "Messy and messy",
    "efficient": "Does things well quickly",
    "inefficient": "Wastes time and effort",
    "effective": "Gets the job done",
    "ineffective": "Does not work",
    "productive": "Gets a lot done",
    "unproductive": "Wastes time",
    "creative": "Makes new things",
    "uncreative": "Does not innovate",
    "imaginative": "Has good imagination",
    "practical": "Realistic and useful",
    "impractical": "Not realistic",
    "logical": "Makes sense",
    "illogical": "Does not make sense",
    "reasonable": "Fair and sensible",
    "unreasonable": "Not fair or sensible",
    "rational": "Based on reason",
    "irrational": "Not based on reason",
    "sensitive": "Feels things deeply",
    "insensitive": "Does not notice feelings",
    "emotional": "Shows strong feelings",
    "emotionless": "Does not show feelings",
    "intelligent": "Smart and clever",
    " unintelligent": "Not smart",
    "wise": "Has good judgment",
    "foolish": "Not wise",
    "clever": "Quick thinking",
    "bright": "Smart (usually young people)",
    "brilliant": "Extremely smart",
    "stupid": "Not smart",
    "silly": "Fun but not smart",
    "dumb": "Cannot speak or not smart",
    "smart": "Intelligent and quick",
    "intelligent": "Has good brainpower",
    "genius": "Extremely talented",
    "talented": "Has special skills",
    "skilled": "Has learned abilities",
    "unskilled": "No special abilities",
    "gifted": "Naturally talented",
    "average": "Normal and typical",
    "ordinary": "Not special",
    "extraordinary": "Very unusual",
    "remarkable": "Worth noting",
    "outstanding": "Exceptionally good",
    "excellent": "Very very good",
    "superb": "Extremely good",
    "magnificent": "Impressive and grand",
    "splendid": "Very impressive",
    "wonderful": "Very good and delightful",
    "marvelous": "Wonderful and amazing",
    "fabulous": "Extremely good",
    "fantastic": "Really great",
    "incredible": "Hard to believe",
    "unbelievable": "Seems impossible",
    "spectacular": "Impressive display",
    "phenomenal": "Extraordinary and remarkable",
    "terrific": "Wonderful and exciting",
    "tremendous": "Huge and impressive",
    "enormous": "Very very big",
    "huge": "Very big",
    "giant": "Extremely big",
    "massive": "Large and heavy",
    "immense": "Very large in size",
    "vast": "Very wide and large",
    "enormous": "Way bigger than normal",
    "tiny": "Very very small",
    "little": "Small in size",
    "small": "Not big",
    "miniature": "Very small version",
    "mini": "Short for miniature",
    "microscopic": "So small you need microscope",
    "microscopic": "Extremely small",
    "petite": "Small and slender (usually people)",
    "compact": "Small but complete",
    "petite": "Small and trim",
    "compact": "Small and efficient",
    "lean": "Thin but strong",
    "slim": "Thin and attractive",
    "skinny": "Too thin",
    "plump": "Round and full",
    "chubby": "A bit overweight",
    "stout": "Thick and strong",
    "stocky": "Short and strong",
    "obese": "Very overweight (medical)",
    "overweight": "Above normal weight",
    "underweight": "Below normal weight",
    "average": "Normal weight",
    "medium": "In the middle",
    "medium-sized": "Neither big nor small",
}

def get_english_thought(word_en, word_zh):
    """获取英语思维记忆提示"""
    word_lower = word_en.lower().strip()
    
    # 直接匹配
    if word_lower in ENGLISH_THOUGHTS:
        return ENGLISH_THOUGHTS[word_lower]
    
    # 短语匹配
    if word_lower in ENGLISH_THOUGHTS:
        return ENGLISH_THOUGHTS[word_lower]
    
    # 找不到，返回空
    return ""

# 测试
test_words = ["shoes", "hat", "wake up", "happy", "run", "apple"]
for w in test_words:
    tip = get_english_thought(w, "")
    print(f"{w}: {tip if tip else '(空)'}")
