# -*- coding: utf-8 -*-
"""
快速修复记忆提示 - 批量替换
"""
import re
import glob
import os

# 替换规则：简单翻译 -> 英文思维
REPLACEMENTS = {
    "记住'shoes'的英文表达": "shoes：鞋，-s=复数，穿脚上的",
    "记住'coat'的英文表达": "coat：外套，像涂层裹身",
    "记住'pillow'的英文表达": "pillow：枕头，支撑头的软垫",
    "记住'blanket'的英文表达": "blanket：保暖覆盖物，像毯子",
    "记住'alarm clock'的英文表达": "alarm=警报，clock=钟，闹钟",
    "记住'lazy'的英文表达": "lazy：懒惰，la=懒zy=自",
    "记住'hungry'的英文表达": "hungry：饿，肚子空空",
    "记住'thorsty'的英文表达": "thirsty：渴，口干想喝",
    "记住'noodles'的英文表达": "noodles：面条，noodle的复数",
    "记住'apple'的英文表达": "apple：苹果，app=应用le=小",
    "记住'plate'的英文表达": "plate：平底盘，像平板",
    "记住'bowl'的英文表达": "bowl：碗，碗状容器",
    "记住'cup'的英文表达": "cup：杯子，喝水杯",
    "记住'bike'的英文表达": "bike：两轮车，bi=两ke=轮",
    "记住'traffic'的英文表达": "traffic：路上的人车，traff=路",
    "记住'far'的英文表达": "far：远，fa=远r=距离",
    "记住'near'的英文表达": "near：近，ne=近ar=近的",
    "记住'principal'的英文表达": "principal：校长，prin=首要cip=领导",
    "记住'chalk'的英文表达": "chalk：粉笔，cha=粉lk=块",
    "记住'spell'的英文表达": "spell：拼写，sp=拼ell=写",
    "记住'page'的英文表达": "page：页码，pa=页ge=码",
    "记住'sentence'的英文表达": "sentence：完整句子，sent=送ence=状态",
    "记住'picture'的英文表达": "picture：图画，pic=画ture=物品",
    "记住'jump'的英文表达": "jump：跳，ju=跳mp=跳起",
    "记住'hallway'的英文表达": "hallway：走廊，hall=大厅way=路",
    "记住'ground'的英文表达": "ground：地面，gr=地ound=表面",
    "记住'drink'的英文表达": "drink：喝，dr=喝ink=拟声",
    "记住'snack'的英文表达": "snack：小份食物，sn=小ack=吃",
    "记住'meal'的英文表达": "meal：一顿饭，me=我al=全部",
    "记住'tasty'的英文表达": "tasty：好吃，taste=味道-y=...的",
    "记住'spicy'的英文表达": "spicy：辣，spice=香料-y=...的",
    "记住'lazy'的英文表达": "lazy：懒惰，la=懒zy=自",
    "记住'fork'的英文表达": "fork：叉子，fo=叉rk=餐具",
    "记住'spoon'的英文表达": "spoon：勺子，sp=勺oon=长勺",
    "记住'knife'的英文表达": "knife：刀，kn=切ife=小刀",
    "记住'yummy'的英文表达": "yummy：好吃，yum=拟声-y=...的",
    "记住'ball'的英文表达": "ball：球，bal=球l=圆",
    "记住'kick'的英文表达": "kick：踢，ki=踢ck=脚踢",
    "记住'exercise'的英文表达": "exercise：锻炼，ex=出er=人cise=练",
    "记住'storybook'的英文表达": "storybook：故事书，story=故事book=书",
    "记住'magazine'的英文表达": "magazine：杂志，magaz=杂志ine=物",
    "记住'shelf'的英文表达": "shelf：架子，she=搁lf=架子",
    "记住'librarian'的英文表达": "librarian：图书管理员，libr=书arian=人",
    "记住'search'的英文表达": "search：搜索，sea=海rch=寻找",
    "记住'author'的英文表达": "author：作者，auth=创作or=人",
    "记住'count'的英文表达": "count：数，cou=数nt=数",
    "记住'silence'的英文表达": "silence：安静，sil=静ence=状态",
    "记住'wash'的英文表达": "wash：洗，wa=洗sh=冲",
    "记住'mom'的英文表达": "mom：妈妈，mo=妈妈m=妈",
    "记住'dad'的英文表达": "dad：爸爸，da=爸爸d=爸",
    "记住'parents'的英文表达": "parents：父母，parent=双亲s=复数",
    "记住'grandma'的英文表达": "grandma：奶奶，grand=大ma=妈",
    "记住'grandpa'的英文表达": "grandpa：爷爷，grand=大pa=爷",
    "记住'welcome'的英文表达": "welcome：欢迎，wel=好come=来",
    "记住'thank you'的英文表达": "thank you：谢谢，th=谢ank=谢",
    "记住'please'的英文表达": "please：请，pl=请ease=容易",
    "记住'more'的英文表达": "more：更多，mo=更re=多",
    "记住'enough'的英文表达": "enough：足够，en=足ough=够",
    "记住'cook'的英文表达": "cook：烹饪，co=厨ok=做饭",
    "记住'set the table'的英文表达": "set the table：摆桌子，set=摆table=桌",
    "记住'glass'的英文表达": "glass：玻璃杯，gl=玻璃ass=杯",
    "记住'napkin'的英文表达": "napkin：餐巾，nap=餐巾kin=小",
    "记住'fresh'的英文表达": "fresh：新鲜，fr=新esh=新鲜",
    "记住'ask for'的英文表达": "ask for：请求，ask=问for=要",
    "记住'enjoy'的英文表达": "enjoy：享受，en=使joy=乐",
    "记住'watch TV'的英文表达": "watch TV：看电视，watch=看TV=电视",
    "记住'movie'的英文表达": "movie：电影，mo=电vie=影",
    "记住'chat'的英文表达": "chat：聊天，ch=聊at=聊",
    "记住'music'的英文表达": "music：音乐，mu=音sic=乐",
    "记住'sing'的英文表达": "sing：唱歌，si=唱ng=歌",
    "记住'dance'的英文表达": "dance：跳舞，da=跳nce=动",
    "记住'photo'的英文表达": "photo：照片，ph=照oto=片",
    "记住'pet'的英文表达": "pet：宠物，pe=宠t=物",
    "记住'hug'的英文表达": "hug：拥抱，hu=抱g=抱",
    "记住'kiss'的英文表达": "kiss：亲吻，ki=亲ss=吻",
    "记住'nice'的英文表达": "nice：好的，ni=好ce=的",
    "记住'comfy'的英文表达": "comfy：舒服，comfortable简化",
    "记住'fun'的英文表达": "fun：有趣，fu=有趣n=乐",
    "记住'math'的英文表达": "math：数学，ma=数th=学",
    "记住'English'的英文表达": "English：英语，Eng=英lish=语言",
    "记住'Chinese'的英文表达": "Chinese：中文，Chi=中nese=语",
    "记住'correct'的英文表达": "correct：正确，cor=正确rect=正",
    "记住'again'的英文表达": "again：再，ag=再ain=一次",
    "记住'clear'的英文表达": "clear：清楚，cl=清ear=楚",
    "记住'concentrate'的英文表达": "concentrate：专心，con=集中cent=心rate=专注",
    "记住'focus'的英文表达": "focus：专注，fo=专cus=心",
    "记住'sleep'的英文表达": "sleep：睡觉，sl=睡eep=休息",
    "记住'wash face'的英文表达": "wash face：洗脸，wash=洗face=脸",
    "记住'dream'的英文表达": "dream：做梦，dr=做梦eam=梦",
    "记住'sleepy'的英文表达": "sleepy：困，sleep=睡-y=...的",
    "记住'tomorrow'的英文表达": "tomorrow：明天，to=明morrow=天",
    "记住'Saturday'的英文表达": "Saturday：周六，Sat=六urday=天",
    "记住'Sunday'的英文表达": "Sunday：周日，Sun=日day=天",
    "记住'cinema'的英文表达": "cinema：电影院，cine=电影ma=场所",
    "记住'shop'的英文表达": "shop：商店，sh=商op=铺",
    "记住'ride'的英文表达": "ride：骑，ri=骑de=车",
    "记住'cash'的英文表达": "cash：现金，ca=现金sh=钱",
    "记住'toy'的英文表达": "toy：玩具，to=玩y=物",
    "记住'size'的英文表达": "size：尺寸，si=尺ze=寸",
    "记住'fit'的英文表达": "fit：合适，fi=适t=的",
    "记住'cost'的英文表达": "cost：花费，co=花st=费",
    "记住'menu'的英文表达": "menu：菜单，men=男u=你人们看",
    "记住'bill'的英文表达": "bill：账单，bi=账ll=两个零",
    "记住'tip'的英文表达": "tip：小费，ti=小p=费",
    "记住'headache'的英文表达": "headache：头痛，head=头ache=痛",
    "记住'cough'的英文表达": "cough：咳嗽，co=咳ugh=嗽",
    "记住'pain'的英文表达": "pain：疼痛，pa=痛in=疼",
    "记住'hurt'的英文表达": "hurt：受伤，hu=伤rt=痛",
    "记住'stomachache'的英文表达": "stomachache：胃痛，stom=胃ach=痛",
    "记住'toothache'的英文表达": "toothache：牙痛，tooth=牙ache=痛",
    "记住'checkup'的英文表达": "checkup：检查，check=检查up=完",
    "记住'boat'的英文表达": "boat：船，bo=船at=在",
    "记住'bench'的英文表达": "bench：长凳，ben=长ch=凳",
    "记住'slide'的英文表达": "slide：滑梯，sl=滑ide=梯",
    "记住'climb'的英文表达": "climb：爬，cl=爬imb=山",
    "记住'sunny'的英文表达": "sunny：晴朗，sun=太阳ny=...的",
    "记住'cloudy'的英文表达": "cloudy：多云，cloud=云y=...的",
    "记住'windy'的英文表达": "windy：有风，wind=风y=...的",
    "记住'get on'的英文表达": "get on：上车，get=上on=上",
    "记住'seat'的英文表达": "seat：座位，se=座at=位",
    "记住'ticket'的英文表达": "ticket：票，tick=勾et=小票",
    "记住'crowded'的英文表达": "crowded：拥挤，crowd=人群ed=...的",
    "记住'fare'的英文表达": "fare：票价，fa=费re=票价",
    "记住'last'的英文表达": "last：上一个，la=上st=的",
    "记住'next'的英文表达": "next：下一个，ne=下xt=的",
    "记住'rush hour'的英文表达": "rush hour：高峰期，rush=冲hour=小时",
    "记住'schedule'的英文表达": "schedule：时间表，sche=时间dule=表",
    "记住'plane'的英文表达": "plane：飞机，pla=平ne=飞行器",
    "记住'ship'的英文表达": "ship：轮船，shi=船p=泊",
    "记住'car'的英文表达": "car：汽车，ca=车r=小",
    "记住'suitcase'的英文表达": "suitcase：行李箱，suit=套装case=箱",
    "记住'map'的英文表达": "map：地图，ma=图p=地图",
    "记住'souvenir'的英文表达": "souvenir：纪念品，souve=纪念nir=品",
    "记住'guide'的英文表达": "guide：导游，gui=导de=人",
    "记住'hello'的英文表达": "hello：你好，he=你llo=好",
    "记住'message'的英文表达": "message：信息，mes=信sage=息",
    "记住'sorry'的英文表达": "sorry：对不起，so=对rry=不起",
    "记住'goodbye'的英文表达": "goodbye：再见，good=好bye=再见",
    "记住'urgent'的英文表达": "urgent：紧急，ur=紧gent=急",
    "记住'mobile'的英文表达": "mobile：手机，mo=手机bile=移动",
    "记住'ring'的英文表达": "ring：响，ri=响ng=铃",
    "记住'available'的英文表达": "available：有空的，avail=可用able=...的",
    "记住'gift'的英文表达": "gift：礼物，gi=礼ft=物",
    "记住'celebrate'的英文表达": "celebrate：庆祝，cele=庆祝brate=庆祝",
    "记住'cake'的英文表达": "cake：蛋糕，ca=蛋糕ke=可口",
    "记住'smile'的英文表达": "smile：微笑，sm=微ile=笑",
    "记住'Christmas'的英文表达": "Christmas：圣诞节，Christ=基督mas=节",
    "记住'fireworks'的英文表达": "fireworks：烟花，fire=火works=作品",
    "记住'routine'的英文表达": "routine：常规，rou=常规tine=惯例",
    "记住'stretch'的英文表达": "stretch：伸展，str=拉etch=伸",
    "记住'boot'的英文表达": "boot：靴子，bo=靴ot=子",
    "记住'neat'的英文表达": "neat：整洁，ne=整at=洁",
    "记住'tidy'的英文表达": "tidy：整洁，ti=整洁dy=的",
    "记住'energetic'的英文表达": "energetic：精力充沛，energy=能量tic=...的",
    "记住'habit'的英文表达": "habit：习惯，ha=习bit=惯",
    "记住'efficient'的英文表达": "efficient：高效，ef=效率fic=做ient=的",
    "记住'ingredient'的英文表达": "ingredient：食材，in=进入gred=配方ient=物",
    "记住'yogurt'的英文表达": "yogurt：酸奶，yo=哟gurt=奶",
    "记住'cereal'的英文表达": "cereal：谷物早餐，cer=谷eal=吃",
    "记住'porridge'的英文表达": "porridge：粥，po=碗rridge=脊",
    "记住'fridge'的英文表达": "fridge：冰箱，fr=冷idge=储存",
    "记住'microwave'的英文表达": "microwave：微波炉，micro=微wave=波",
    "记住'stove'的英文表达": "stove：炉子，st=炉ove=火",
    "记住'pan'的英文表达": "pan：平底锅，pa=平n=锅",
    "记住'pot'的英文表达": "pot：锅，po=锅t=壶",
    "记住'chef'的英文表达": "chef：厨师，ch=厨师ef=大厨",
    "记住'nutritious'的英文表达": "nutritious：有营养，nutrition=营养ous=...的",
    "记住'balance'的英文表达": "balance：平衡，ba=平lance=衡",
    "记住'digest'的英文表达": "digest：消化，di=消gest=消化",
    "记住'commute'的英文表达": "commute：通勤，com=共同mute=交换",
    "记住'subway'的英文表达": "subway：地铁，sub=地下way=路",
    "记住'route'的英文表达": "route：路线，rou=路te=线",
    "记住'pavement'的英文表达": "pavement：人行道，pave=铺ment=路",
    "记住'distance'的英文表达": "distance：距离，di=距stance=离",
    "记住'congested'的英文表达": "congested：拥挤，con=一起gest=拥挤ed=...的",
    "记住'pedestrian'的英文表达": "pedestrian：行人，ped=行人estrian=...的",
    "记住'convenient'的英文表达": "convenient：方便，con=共同ven=来ient=的",
    "记住'accessible'的英文表达": "accessible：方便到达，ac=到cess=走ible=能",
    "记住'textbook'的英文表达": "textbook：教科书，text=文本book=书",
    "记住'dictionary'的英文表达": "dictionary：词典，dic=词tionary=典",
    "记住'projector'的英文表达": "projector：投影仪，project=投影or=器",
    "记住'screen'的英文表达": "screen：屏幕，sc=屏reen=幕",
    "记住'assignment'的英文表达": "assignment：作业，assign=分配ment=物",
    "记住'collaborate'的英文表达": "collaborate：合作，col=一起labor=劳动ate=做",
    "记住'curious'的英文表达": "curious：好奇，cur=好奇ious=...的",
    "记住'participate'的英文表达": "participate：参加，part=部分icip=参加ate=做",
    "记住'progress'的英文表达": "progress：进步，pro=向前gress=步",
    "记住'encourage'的英文表达": "encourage：鼓励，en=给courage=勇气",
    "记住'fluent'的英文表达": "fluent：流利，flu=流ent=...的",
    "记住'confident'的英文表达": "confident：自信，con=全fid=信ent=的",
    "记住'comprehension'的英文表达": "comprehension：理解，com=理解pre=前hens=抓ition=状态",
    "记住'analyze'的英文表达": "analyze：分析，an=分析alyze=拆开",
    "记住'summarize'的英文表达": "summarize：总结，sum=总mary=摘要ize=化",
    "记住'conclude'的英文表达": "conclude：总结，con=共同clude=关闭",
    "记住'paraphrase'的英文表达": "paraphrase：改述，para=改phrase=述",
    "记住'translate'的英文表达": "translate：翻译，trans=转late=带",
    "记住'idiom'的英文表达": "idiom：习语，id=习iom=语",
    "记住'phrase'的英文表达": "phrase：短语，ph=短rase=语",
    "记住'memorize'的英文表达": "memorize：记忆，mem=记orize=化",
    "记住'gossip'的英文表达": "gossip：八卦，go=去ssip=聊",
    "记住'corridor'的英文表达": "corridor：走廊，cor=通道ridor=走廊",
    "记住'vending machine'的英文表达": "vending machine：自动售货机，vending=销售machine=机",
    "记住'cola'的英文表达": "cola：可乐，co=可乐la=饮料",
    "记住'energy bar'的英文表达": "energy bar：能量棒，energy=能量bar=棒",
    "记住'stretch legs'的英文表达": "stretch legs：伸腿，stretch=伸legs=腿",
    "记住'breathe'的英文表达": "breathe：呼吸，brea=呼the=气",
    "记住'mental'的英文表达": "mental：心理，men=心tal=的",
    "记住'socialize'的英文表达": "socialize：社交，social=社会ize=化",
    "记住'bond'的英文表达": "bond：联系，bo=联nd=结",
    "记住'cafeteria'的英文表达": "cafeteria：自助餐厅，cafe=咖啡teria=餐厅",
    "记住'canteen'的英文表达": "canteen：食堂，can=能teen=食堂",
    "记住'main course'的英文表达": "main course：主菜，main=主course=菜",
    "记住'fries'的英文表达": "fries：薯条，fri=炸es=复数",
    "记住'beverage'的英文表达": "beverage：饮料，beve=喝rage=料",
    "记住'allergic'的英文表达": "allergic：过敏，aller=过敏gic=...的",
    "记住'vegetarian'的英文表达": "vegetarian：素食者，veget=蔬菜arian=者",
    "记住'calorie'的英文表达": "calorie：卡路里，cal=卡orie=热量",
    "记住'organic'的英文表达": "organic：有机，org=有机anic=...的",
    "记住'athlete'的英文表达": "athlete：运动员，ath=运动lete=员",
    "记住'coach'的英文表达": "coach：教练，co=教练ach=教",
    "记住'warm up'的英文表达": "warm up：热身，warm=热身up=上",
    "记住'muscle'的英文表达": "muscle：肌肉，mus=肌cle=肉",
    "记住'stamina'的英文表达": "stamina：耐力，sta=耐mina=力",
    "记住'flexible'的英文表达": "flexible：灵活，flex=弯曲ible=能",
    "记住'cooperate'的英文表达": "cooperate：合作，co=共同operate=操作",
    "记住'compete'的英文表达": "compete：竞争，com=共同pete=追求",
    "记住'champion'的英文表达": "champion：冠军，cham=冠军pion=者",
    "记住'score'的英文表达": "score：得分，sc=得ore=分",
    "记住'teamwork'的英文表达": "teamwork：团队合作，team=队work=工作",
    "记住'fitness'的英文表达": "fitness：健身，fit=适合ness=状态",
    "记住'endurance'的英文表达": "endurance：耐力，en=持续dur=耐久ance=状态",
    "记住'agility'的英文表达": "agility：敏捷，ag=敏捷ility=能力",
    "记住'catalog'的英文表达": "catalog：目录，cata=目录log=记录",
    "记住'biography'的英文表达": "biography：传记，bio=生graphy=写",
    "记住'encyclopedia'的英文表达": "encyclopedia：百科全书，en= encyclo=循环pedia=知识",
    "记住'article'的英文表达": "article：文章，art=文章icle=小",
    "记住'index'的英文表达": "index：索引，in=索引dex=指示",
    "记住'abstract'的英文表达": "abstract：摘要，abs=抽tract=取",
    "记住'cite'的英文表达": "cite：引用，ci=引te=用",
    "记住'due'的英文表达": "due：截止，du=截止e=的",
    "记住'database'的英文表达": "database：数据库，data=数据base=库",
    "记住'independent'的英文表达": "independent：独立，in=不depen=依赖dent=的",
    "记住'chore'的英文表达": "chore：家务，ch=家ore=活",
    "记住'dishes'的英文表达": "dishes：碗碟，dish=盘es=复数",
    "记住'laundry'的英文表达": "laundry：洗衣，laun=洗dry=干",
    "记住'fold'的英文表达": "fold：折叠，fo=折ld=叠",
    "记住'arrange'的英文表达": "arrange：整理，ar=整理range=排列",
    "记住'prioritize'的英文表达": "prioritize：优先，prior=优先itize=化",
    "记住'deadline'的英文表达": "deadline：截止日期，dead=死line=线",
    "记住'appreciate'的英文表达": "appreciate：感激，ap=感preci=价值ate=化",
    "记住'self-discipline'的英文表达": "self-discipline：自律，self=自己discipline=纪律",
    "记住'productive'的英文表达": "productive：高效，pro=产品ductive=产的",
    "记住'mature'的英文表达": "mature：成熟，ma=成熟ture=的",
    "记住'compliment'的英文表达": "compliment：赞美，com=赞美pli=赞美ment=物",
    "记住'etiquette'的英文表达": "etiquette：礼仪，e=礼仪tiquette=礼节",
    "记住'wholesome'的英文表达": "wholesome：健康，whole=全some=...的",
    "记住'home-cooked'的英文表达": "home-cooked：家常的，home=家cooked=烹饪的",
    "记住'quality time'的英文表达": "quality time：高质量时间，quality=质量time=时间",
    "记住'togetherness'的英文表达": "togetherness：团聚，together=一起ness=状态",
    "记住'cherish'的英文表达": "cherish：珍惜，cher=珍ish=视",
    "记住'harmonious'的英文表达": "harmonious：和谐，harmon=和谐ious=...的",
    "记住'entertainment'的英文表达": "entertainment：娱乐，enter=进入tain=持ment=物",
    "记住'hobby'的英文表达": "hobby：爱好，ho=业bby=爱好",
    "记住'board game'的英文表达": "board game：桌游，board=板game=游戏",
    "记住'jigsaw'的英文表达": "jigsaw：拼图，ji=拼saw=图",
    "记住'craft'的英文表达": "craft：手工艺，cr=手aft=艺",
    "记住'DIY'的英文表达": "DIY：自己动手，Do=做It=它Yourself=自己",
    "记住'bake'的英文表达": "bake：烘焙，ba=烘ke=焙",
    "记住'memories'的英文表达": "memories：回忆，memory=记忆s=复数",
    "记住'treasure'的英文表达": "treasure：珍惜，trea=珍sure=宝",
    "记住'compromise'的英文表达": "compromise：妥协，com=共同promise=承诺",
    "记住'intimacy'的英文表达": "intimacy：亲密，int=亲密imacy=关系",
    "记住'investigate'的英文表达": "investigate：调查，in=调查vestigate=调查",
    "记住'evaluate'的英文表达": "evaluate：评估，e=评估value=价值ate=化",
    "记住'illustrate'的英文表达": "illustrate：说明，il=说明lustrate=照亮",
    "记住'demonstrate'的英文表达": "demonstrate：演示，de=演示monstrate=显示",
    "记住'solve'的英文表达": "solve：解决，so=解lve=决",
    "记住'calculate'的英文表达": "calculate：计算，cal=计算culate=算",
    "记住'formula'的英文表达": "formula：公式，for=公式mula=式",
    "记住'diagram'的英文表达": "diagram：图表，dia=图表gram=图",
    "记住'graph'的英文表达": "graph：图表，gr=图表aph=图",
    "记住'proof'的英文表达": "proof：证明，pr=证oof=明",
    "记住'logical'的英文表达": "logical：逻辑，log=逻辑ical=...的",
    "记住'systematic'的英文表达": "systematic：系统，system=系统atic=...的",
    "记住'thorough'的英文表达": "thorough：彻底，thoro=彻底ugh=的",
    "记住'calm'的英文表达": "calm：平静，ca=平lm=静",
    "记住'cozy'的英文表达": "cozy：舒适，co=舒zy=适",
    "记住'settle'的英文表达": "settle：定居，set=定居tle=安",
    "记住'drift'的英文表达": "drift：漂流，dr=漂ift=流",
    "记住'ambient'的英文表达": "ambient：环境，amb=环境ient=...的",
    "记住'humid'的英文表达": "humid：潮湿，hu=湿mid=潮湿",
    "记住'ventilate'的英文表达": "ventilate：通风，vent=通ilate=化",
    "记住'tranquil'的英文表达": "tranquil：安静，tran=平静quil=静",
    "记住'itinerary'的英文表达": "itinerary：行程，it=行inerary=路线",
    "记住'excursion'的英文表达": "excursion：远足，ex=出去cursion=跑",
    "记住'aquarium'的英文表达": "aquarium：水族馆，aqua=水rium=馆",
    "记住'concert'的英文表达": "concert：音乐会，con=共同cert=和谐",
    "记住'festival'的英文表达": "festival：节日，fest=节日ival=活动",
    "记住'leisure'的英文表达": "leisure：休闲，lei=休sure=闲",
    "记住'adventure'的英文表达": "adventure：冒险，ad=加强venture=冒险",
    "记住'budget'的英文表达": "budget：预算，bud=预get=准备",
    "记住'discount'的英文表达": "discount：折扣，dis=不count=计算",
    "记住'bargain'的英文表达": "bargain：讨价还价，bar=讨gain=价",
    "记住'exchange'的英文表达": "exchange：交换，ex=出change=换",
    "记住'authentic'的英文表达": "authentic：正宗，authen=真tic=...的",
    "记住'genuine'的英文表达": "genuine：真正的，genu=真ine=...的",
    "记住'brand'的英文表达": "brand：品牌，br=品and=牌",
    "记住'mall'的英文表达": "mall：商场，ma=商ll=场",
    "记住'boutique'的英文表达": "boutique：精品店，bou=精品tique=店",
    "记住'delivery'的英文表达": "delivery：送货，deli=送very=到达",
    "记住'installment'的英文表达": "installment：分期付款，install=装ment=款",
    "记住'comparison'的英文表达": "comparison：比较，com=共同parison=比",
    "记住'warranty'的英文表达": "warranty：保修，war=保ranty=证",
    "记住'cuisine'的英文表达": "cuisine：菜肴，cui=烹sine=饪",
    "记住chef's special": "chef's special：招牌菜，chef=厨师special=特色",
    "记住'mild'的英文表达": "mild：清淡，mi=清ld=淡",
    "记住'greasy'的英文表达": "greasy：油腻，grease=油y=...的",
    "记住'raw'的英文表达": "raw：生的，ra=生w=的",
    "记住'well-done'的英文表达": "well-done：全熟，well=好done=熟",
    "记住'medium'的英文表达": "medium：中等，med=中ium=程度",
    "记住'rare'的英文表达": "rare：三分熟，ra=稀re=的",
    "记住'portion size'的英文表达": "portion size：份量，portion=份size=量",
    "记住'takeaway'的英文表达": "takeaway：外卖，take=拿away=走",
    "记住'ambiance'的英文表达": "ambiance：氛围，amb=氛围iance=环境",
    "记住'flavor'的英文表达": "flavor：味道，fla=味vor=道",
    "记住'savory'的英文表达": "savory：咸的，sa=咸vory=味",
    "记住'symptom'的英文表达": "symptom：症状，sym=症ptom=状",
    "记住'diagnosis'的英文表达": "diagnosis：诊断，diag=诊断nosis=断",
    "记住'pharmacy'的英文表达": "pharmacy：药房，phar=药macy=房",
    "记住'appointment'的英文表达": "appointment：预约，appoint=约定ment=物",
    "记住'emergency'的英文表达": "emergency：急诊，e=紧急merg=出现ency=状态",
    "记住'allergy'的英文表达": "allergy：过敏，aller=过敏gy=症",
    "记住'chronic'的英文表达": "chronic：慢性，chr=慢onic=...的",
    "记住'acute'的英文表达": "acute：急性，ac=急ute=的",
    "记住'heal'的英文表达": "heal：治愈，he=治al=愈",
    "记住'therapy'的英文表达": "therapy：治疗，thera=治疗py=法",
    "记住'surgery'的英文表达": "surgery：手术，sur=手术gery=外科",
    "记住'ward'的英文表达": "ward：病房，wa=病rd=房",
    "记住'clinic'的英文表达": "clinic：诊所，cl=诊所inic=诊所",
    "记住'outpatient'的英文表达": "outpatient：门诊，out=外patient=病人",
    "记住'insurance'的英文表达": "insurance：保险，in=保sure=险ance=费",
    "记住'scenery'的英文表达": "scenery：风景，scen=景ery=物",
    "记住'landscape'的英文表达": "landscape：景观，land=陆地scape=景",
    "记住'trail'的英文表达": "trail：步道，tr=步ail=小径",
    "记住'path'的英文表达": "path：小路，pa=小th=路",
    "记住'picnic area'的英文表达": "picnic area：野餐区，picnic=野餐area=区",
    "记住'facility'的英文表达": "facility：设施，fac=设ility=备",
    "记住'maintenance'的英文表达": "maintenance：维护，main=主tenance=持",
    "记住'preserve'的英文表达": "preserve：保护，pre=预先serve=保存",
    "记住'wildlife'的英文表达": "wildlife：野生动物，wild=野life=动物",
    "记住'ecosystem'的英文表达": "ecosystem：生态系统，eco=生态system=系统",
    "记住'squirrel'的英文表达": "squirrel：松鼠，squi=松rrel=鼠",
    "记住'duck'的英文表达": "duck：鸭子，du=鸭ck=子",
    "记住'swan'的英文表达": "swan：天鹅，sw=天鹅an=的",
    "记住'paddle'的英文表达": "paddle：划船，pa=划ddle=桨",
    "记住'breeze'的英文表达": "breeze：微风，br=微eeze=风",
    "记住'shade'的英文表达": "shade：阴凉，sh=阴ade=处",
    "记住'serene'的英文表达": "serene：宁静，se=宁rene=静",
    "记住'harmony'的英文表达": "harmony：和谐，har=和mony=谐",
    "记住'transport'的英文表达": "transport：交通，trans=转port=运",
    "记住'transit'的英文表达": "transit：运输，tran=运sit=输",
    "记住'timetable'的英文表达": "timetable：时刻表，time=时间table=表",
    "记住'frequency'的英文表达": "frequency：频率，fre=频quency=次",
    "记住'peak hour'的英文表达": "peak hour：高峰时段，peak=高峰hour=小时",
    "记住'off-peak'的英文表达": "off-peak：非高峰，off=非peak=峰",
    "记住'transfer point'的英文表达": "transfer point：换乘点，transfer=换point=点",
    "记住'priority seat'的英文表达": "priority seat：优先座，priority=优先seat=座",
    "记住'standing room'的英文表达": "standing room：站立区，standing=站room=区",
    "记住'delay'的英文表达": "delay：延误，de=延lay=误",
    "记住'punctual'的英文表达": "punctual：准时，punct=准ual=...的",
    "记住'terminal'的英文表达": "terminal：终点站，term=终inal=站",
    "记住'hostel'的英文表达": "hostel：旅舍，host=主人el=小",
    "记住'guesthouse'的英文表达": "guesthouse：招待所，guest=客house=屋",
    "记住'tour guide'的英文表达": "tour guide：导游，tour=旅行guide=引",
    "记住'exchange rate'的英文表达": "exchange rate：汇率，exchange=兑换rate=率",
    "记住'currency'的英文表达": "currency：货币，cur=流通rency=币",
    "记住'explore'的英文表达": "explore：探索，ex=出去plore=探",
    "记住'memorable'的英文表达": "memorable：难忘，mem=记orable=值得",
    "记住'available'的英文表达": "available：有空，avail=可用able=能",
    "记住'contact'的英文表达": "contact：联系，con=共同tact=触",
    "记住'callback'的英文表达": "callback：回拨，back=回call=拨",
    "记住'voicemail'的英文表达": "voicemail：语音信箱，voice=声mail=邮件",
    "记住'dial'的英文表达": "dial：拨号，di=拨al=号",
    "记住'extension'的英文表达": "extension：分机，ex=分tension=机",
    "记住'operator'的英文表达": "operator：接线员，operate=操作or=者",
    "记住'disconnected'的英文表达": "disconnected：断线，dis=不connect=连接ed=的",
    "记住'cut off'的英文表达": "cut off：挂断，cut=切off=断",
    "记住'clarify'的英文表达": "clarify：澄清，cl=澄清arify=明",
    "记住'confirm'的英文表达": "confirm：确认，con=确认firm=定",
    "记住'inconvenience'的英文表达": "inconvenience：不便，in=不convenience=方便",
    "记住'follow up'的英文表达": "follow up：跟进，follow=跟随up=上",
    "记住'update'的英文表达": "update：更新，up=更新date=日期",
    "记住'consult'的英文表达": "consult：咨询，con=共同sult=议",
    "记住'brief'的英文表达": "brief：简报，br=简ief=短",
    "记住'custom'的英文表达": "custom：习俗，cus=习tom=俗",
    "记住'ritual'的英文表达": "ritual：仪式，rit=仪式ual=的",
    "记住'ceremony'的英文表达": "ceremony：典礼，cere=典礼mony=式",
    "记住'feast'的英文表达": "feast：盛宴，fe=盛ast=宴",
    "记住'banquet'的英文表达": "banquet：宴会，ban=宴quet=会",
    "记住'ornament'的英文表达": "ornament：装饰，or=装饰nament=物",
    "记住'lantern'的英文表达": "lantern：灯笼，lan=灯tern=笼",
    "记住'confetti'的英文表达": "confetti：彩纸，con=彩fetti=纸屑",
    "记住'tribute'的英文表达": "tribute：敬意，tri=敬意bute=献",
    "记住'gratitude'的英文表达": "gratitude：感激，gra=感激titude=状态",
    "记住'exchange gifts'的英文表达": "exchange gifts：交换礼物，exchange=交换gifts=礼物",
    
    # 简单的翻译格式 -> 英文思维
    "shirt=衬衫，短上衣": "shirt：上身穿的短上衣，sh=上irt=衣",
    "pant=下垂裤(古)，s=复数，下垂到腿的裤子": "pant：裤子，pan=下垂t=裤",
    "sock=袜子，s=复数，袜子": "sock：袜子，穿脚上的薄套",
    "hat=帽子，头部遮盖": "hat：帽子，盖在头上的",
    "jacket=短外套": "jacket：短外套，jack=千斤顶et=小",
    "desk=桌子，有抽屉的工作台": "desk：书桌，de=书sk=桌",
    "bed=床，躺卧休息的家具": "bed：床，be=躺d=铺",
    "mirror=镜子，反映影像": "mirror：镜子，mir=看ror=反照",
}

def fix_html_files():
    """批量修复所有HTML文件"""
    import sys
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    
    html_files = glob.glob('2026-*.html') + glob.glob('2027-*.html')
    html_files.sort()
    
    fixed_count = 0
    for filepath in html_files:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original = content
        for old, new in REPLACEMENTS.items():
            content = content.replace(old, new)
        
        if content != original:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            fixed_count += 1
            print(f"[OK] {filepath}")
        else:
            print(f"[--] {filepath}")
    
    print(f"\nTotal: Fixed {fixed_count} files")


if __name__ == '__main__':
    fix_html_files()
